version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: conciliacion_db
    restart: always
    environment:
      POSTGRES_USER: user_pyme
      POSTGRES_PASSWORD: password_pyme
      POSTGRES_DB: conciliacion_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: